<section class="jumbotron subhead" id="overview">
    <div class="container">
        <h1>Compartilhe seu conhecimento para toda a empresa!</h1>
        <p class="lead">Documentos, video-aulas, artigos, tudo para ajudar seu desempenho no dia a dia</p>

        <form class="form-search">
            <input type="text" class="input-xxlarge search-query" placeholder="O que você procura?">
        </form>    
    </div>
</section>