<ul class="breadcrumb">
    <li><a href="#">Visão Geral</a> <span class="divider">/</span></li>
    <li class="active">Ti</li>
</ul>

<div class="row-fluid">
    <div class="span12">
        <h2>Tecnologia da Informação</h2>

        <hr>
    </div>
</div>


<div class="row">
    <div class="span3">
        <div class="tree">
            <ul>
                <li>
                    <span>Softwares TOTVS</span>
                    <ul>
                        <li><span><i class="icon-minus-sign"></i> RM Nucleus</span>
                            <ul>
                                <li><span>Cadastros</span>
                                    <ul>
                                        <li><a href="#">Cadastro de clientes</a></li>
                                        <li><a href="#">Cadastro de Produtos</a></li>
                                        <li><a href="#">Cadastro de Transportadoras</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><span><i class="icon-minus-sign"></i> RM Labore</span></li>
                        <li><span><i class="icon-minus-sign"></i> RM Liber</span></li>
                        <li><span><i class="icon-minus-sign"></i> RM Factor</span></li>
                        <li><span><i class="icon-minus-sign"></i> RM Fluxus</span></li>
                        <li><span><i class="icon-minus-sign"></i> RM Chronus</span></li>
                        <li><span><i class="icon-minus-sign"></i> Gerador de relaórios</span></li>
                        <li><span><i class="icon-minus-sign"></i> Cubos</span></li>
                    </ul>
                </li>

                <li><span>Internet e comunitações</span></li>
                <li><span>Servidores</span></li>
                <li><span>Manutenção de equipamentos</span></li>
                <li><span>Operação do computador</span></li>
            </ul>
        </div>

    </div>
</div>
