<div class="row-fluid">
    <h2>Nova Área</h2>

    <hr>

    <form method="post" class="form-horizontal" id="usuario">
        <div class="row-fluid">
            <div class="span1 txtCenter">
                <i class="icon-list icon-3x muted"></i>
            </div>
            <div class="span11">
                <div class="control-group">
                    <label class="control-label">
                        <label for="name">Nome</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="name" class="input-xlarge">							
                    </div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
            <a href="/areas" class="btn">Cancelar</a>
        </div>

    </form>

    <script type="text/javascript">
        $('#usuario').validate({
            rules: {
                name: {required: true, minLenght: 2}
            }
        });
    </script>  

</div>
